### ISSUE TITLE
[mqtt-sparkplug] from topic to groups

### ISSUE THREAD

**Issue by gaillarddamien** [riclolsen/json-scada#87]
Given the general MQTT-Sparkplug topic structure

```
namespace/group_id/message_type/edge_node_id/[device_id]
```

I was surprised the "auto tag" feature would break the topic into the following:

- `group1`: `MQTT:1200`
- `group2`: `group_id`
- `group3`:

rather than what I was expecting:

- `group1`: `group_id`
- `group2`: `edge_node_id`
- `group3`: `device_id`

`MQTT:1200` does not appear to be very helpful (we know it from `protocolSourceConnectionNumber`), and I feel at least `edge_node_id` is missing.

It could look like [this](https://github.com/riclolsen/json-scada/compare/master...gaillarddamien:json-scada:mqtt-sparkplug-topic-splitting?expand=1).

Am I missing something? or making wrong assumptions? 
Thank you very much for all you've done.

**Comment by riclolsen** [comment]
Hi Damien,
The problem is that tags should be unique and using just group_id//edge_node_id/device_id the tag name can be repeated on other MQTT brokers, like on a different site with the same device structuring. Using the protocolConnectionNumber as a prefix can solve this possible problem. 
Maybe I can add a parameter to make it possible to select different auto naming scheme.
